version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: pr-assign-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_assign
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pr_assign"]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-assign-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      HTTP_SERVER_ADDRESS: "0.0.0.0"
      HTTP_SERVER_PORT: "8080"
      HTTP_SERVER_TIMEOUT: "4s"

      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "pr_assign"
      DB_HOST: "db"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg_data: